// this contains an array of usages from different countries/regions.

const usage = [
  { code: "afk", name: "Afrikaans", id: 1 },
  { code: "afr", name: "African", id: 2 },
  { code: "aka", name: "Akan", id: 3 },
  { code: "alb", name: "Albanian", id: 4 },
  { code: "alg", name: "Algonquin", id: 5 },
  { code: "ame", name: "Indigenous American", id: 6 },
  { code: "amem", name: "New World Mythology", id: 7 },
  { code: "amh", name: "Amharic", id: 8 },
  { code: "anci", name: "Ancient", id: 9 },
  { code: "apa", name: "Apache", id: 10 },
  { code: "ara", name: "Arabic", id: 11 },
  { code: "arm", name: "Armenian", id: 12 },
  { code: "asm", name: "Assamese", id: 13 },
  { code: "ast", name: "Asturian", id: 14 },
  { code: "astr", name: "Astronomy", id: 15 },
  { code: "aus", name: "Indigenous Australian", id: 16 },
  { code: "ava", name: "Avar", id: 17 },
  { code: "aym", name: "Aymara", id: 18 },
  { code: "aze", name: "Azerbaijani", id: 19 },
  { code: "bal", name: "Balinese", id: 20 },
  { code: "bas", name: "Basque", id: 21 },
  { code: "bel", name: "Belarusian", id: 22 },
  { code: "ben", name: "Bengali", id: 23 },
  { code: "ber", name: "Berber", id: 24 },
  { code: "bhu", name: "Bhutanese", id: 25 },
  { code: "bibl", name: "Biblical (All)", id: 26 },
  { code: "bos", name: "Bosnian", id: 27 },
  { code: "bre", name: "Breton", id: 28 },
  { code: "bsh", name: "Bashkir", id: 29 },
  { code: "bul", name: "Bulgarian", id: 30 },
  { code: "bur", name: "Burmese", id: 31 },
  { code: "cat", name: "Catalan", id: 32 },
  { code: "cela", name: "Ancient Celtic", id: 33 },
  { code: "celm", name: "Celtic Mythology", id: 34 },
  { code: "cew", name: "Chewa", id: 35 },
  { code: "cha", name: "Chamorro", id: 36 },
  { code: "che", name: "Chechen", id: 37 },
  { code: "chi", name: "Chinese", id: 38 },
  { code: "chk", name: "Cherokee", id: 39 },
  { code: "cht", name: "Choctaw", id: 40 },
  { code: "chy", name: "Cheyenne", id: 41 },
  { code: "cir", name: "Circassian", id: 42 },
  { code: "cmr", name: "Comorian", id: 43 },
  { code: "com", name: "Comanche", id: 44 },
  { code: "cop", name: "Coptic", id: 45 },
  { code: "cor", name: "Cornish", id: 46 },
  { code: "cre", name: "Cree", id: 47 },
  { code: "cro", name: "Croatian", id: 48 },
  { code: "crs", name: "Corsican", id: 49 },
  { code: "cze", name: "Czech", id: 50 },
  { code: "dan", name: "Danish", id: 51 },
  { code: "dgs", name: "Dagestani", id: 52 },
  { code: "dhi", name: "Dhivehi", id: 53 },
  { code: "dut", name: "Dutch", id: 54 },
  { code: "egya", name: "Ancient Egyptian", id: 55 },
  { code: "egym", name: "Egyptian Mythology", id: 56 },
  { code: "elf", name: "Xmas Elf", id: 57 },
  { code: "eng", name: "English", id: 58 },
  { code: "enga", name: "Anglo-Saxon", id: 59 },
  { code: "esp", name: "Esperanto", id: 60 },
  { code: "est", name: "Estonian", id: 61 },
  { code: "eth", name: "Ethiopian", id: 62 },
  { code: "ewe", name: "Ewe", id: 63 },
  { code: "fae", name: "Faroese", id: 64 },
  { code: "fairy", name: "Fairy", id: 65 },
  { code: "fij", name: "Fijian", id: 66 },
  { code: "fil", name: "Filipino", id: 67 },
  { code: "fin", name: "Finnish", id: 68 },
  { code: "fle", name: "Flemish", id: 69 },
  { code: "fntsg", name: "Gluttakh", id: 70 },
  { code: "fntsm", name: "Monstrall", id: 71 },
  { code: "fntso", name: "Orinami", id: 72 },
  { code: "fntsr", name: "Romanto", id: 73 },
  { code: "fntss", name: "Simitiq", id: 74 },
  { code: "fntst", name: "Tsang", id: 75 },
  { code: "fntsx", name: "Xalaxxi", id: 76 },
  { code: "fre", name: "French", id: 77 },
  { code: "fri", name: "Frisian", id: 78 },
  { code: "ful", name: "Fula", id: 79 },
  { code: "gaa", name: "Ga", id: 80 },
  { code: "gal", name: "Galician", id: 81 },
  { code: "gan", name: "Ganda", id: 82 },
  { code: "geo", name: "Georgian", id: 83 },
  { code: "ger", name: "German", id: 84 },
  { code: "gmca", name: "Ancient Germanic", id: 85 },
  { code: "goth", name: "Goth", id: 86 },
  { code: "gre", name: "Greek", id: 87 },
  { code: "grea", name: "Ancient Greek", id: 88 },
  { code: "grem", name: "Greek Mythology", id: 89 },
  { code: "grn", name: "Greenlandic", id: 90 },
  { code: "gua", name: "Guarani", id: 91 },
  { code: "guj", name: "Gujarati", id: 92 },
  { code: "hau", name: "Hausa", id: 93 },
  { code: "haw", name: "Hawaiian", id: 94 },
  { code: "hb", name: "Hillbilly", id: 95 },
  { code: "heb", name: "Hebrew", id: 96 },
  { code: "hin", name: "Hindi", id: 97 },
  { code: "hippy", name: "Hippy", id: 98 },
  { code: "hist", name: "History", id: 99 },
  { code: "hmo", name: "Hmong", id: 100 },
  { code: "hun", name: "Hungarian", id: 101 },
  { code: "ibi", name: "Ibibio", id: 102 },
  { code: "ice", name: "Icelandic", id: 103 },
  { code: "igb", name: "Igbo", id: 104 },
  { code: "ind", name: "Indian", id: 105 },
  { code: "indm", name: "Hindu Mythology", id: 106 },
  { code: "ing", name: "Ingush", id: 107 },
  { code: "ins", name: "Indonesian", id: 108 },
  { code: "inu", name: "Inuit", id: 109 },
  { code: "iri", name: "Irish", id: 110 },
  { code: "iro", name: "Iroquois", id: 111 },
  { code: "ita", name: "Italian", id: 112 },
  { code: "jap", name: "Japanese", id: 113 },
  { code: "jav", name: "Javanese", id: 114 },
  { code: "jer", name: "Jèrriais", id: 115 },
  { code: "jew", name: "Jewish", id: 116 },
  { code: "kan", name: "Kannada", id: 117 },
  { code: "kaz", name: "Kazakh", id: 118 },
  { code: "khm", name: "Khmer", id: 119 },
  { code: "kig", name: "Kiga", id: 120 },
  { code: "kik", name: "Kikuyu", id: 121 },
  { code: "kk", name: "Kreatyve", id: 122 },
  { code: "kon", name: "Kongo", id: 123 },
  { code: "kor", name: "Korean", id: 124 },
  { code: "kur", name: "Kurdish", id: 125 },
  { code: "kyr", name: "Kyrgyz", id: 126 },
  { code: "lao", name: "Lao", id: 127 },
  { code: "lat", name: "Latvian", id: 128 },
  { code: "lim", name: "Limburgish", id: 129 },
  { code: "lite", name: "Literature", id: 130 },
  { code: "litk", name: "Arthurian Romance", id: 131 },
  { code: "lth", name: "Lithuanian", id: 132 },
  { code: "luh", name: "Luhya", id: 133 },
  { code: "luo", name: "Luo", id: 134 },
  { code: "mac", name: "Macedonian", id: 135 },
  { code: "mag", name: "Maguindanao", id: 136 },
  { code: "mal", name: "Maltese", id: 137 },
  { code: "man", name: "Manx", id: 138 },
  { code: "mao", name: "Maori", id: 139 },
  { code: "map", name: "Mapuche", id: 140 },
  { code: "may", name: "Mayan", id: 141 },
  { code: "mbu", name: "Mbundu", id: 142 },
  { code: "medi", name: "Medieval", id: 143 },
  { code: "mlm", name: "Malayalam", id: 144 },
  { code: "mly", name: "Malay", id: 145 },
  { code: "moh", name: "Mohawk", id: 146 },
  { code: "mon", name: "Mongolian", id: 147 },
  { code: "morm", name: "Mormon", id: 148 },
  { code: "mrt", name: "Marathi", id: 149 },
  { code: "mwe", name: "Mwera", id: 150 },
  { code: "myth", name: "Mythology", id: 151 },
  { code: "nah", name: "Nahuatl", id: 152 },
  { code: "nav", name: "Navajo", id: 153 },
  { code: "nde", name: "Ndebele", id: 154 },
  { code: "neaa", name: "Ancient Near Eastern", id: 155 },
  { code: "neam", name: "Near Eastern Mythology", id: 156 },
  { code: "nep", name: "Nepali", id: 157 },
  { code: "nor", name: "Norwegian", id: 158 },
  { code: "nrm", name: "Norman", id: 159 },
  { code: "nuu", name: "Nuu-chah-nulth", id: 160 },
  { code: "occ", name: "Occitan", id: 161 },
  { code: "odi", name: "Odia", id: 162 },
  { code: "oji", name: "Ojibwe", id: 163 },
  { code: "one", name: "Oneida", id: 164 },
  { code: "oro", name: "Oromo", id: 165 },
  { code: "oss", name: "Ossetian", id: 166 },
  { code: "pas", name: "Pashto", id: 167 },
  { code: "pcd", name: "Picard", id: 168 },
  { code: "per", name: "Persian", id: 169 },
  { code: "pets", name: "Pet", id: 170 },
  { code: "pin", name: "Pintupi", id: 171 },
  { code: "pol", name: "Polish", id: 172 },
  { code: "popu", name: "Popular Culture", id: 173 },
  { code: "por", name: "Portuguese", id: 174 },
  { code: "pow", name: "Powhatan", id: 175 },
  { code: "pun", name: "Punjabi", id: 176 },
  { code: "que", name: "Quechua", id: 177 },
  { code: "rap", name: "Rapper", id: 178 },
  { code: "rmn", name: "Romanian", id: 179 },
  { code: "roma", name: "Ancient Roman", id: 180 },
  { code: "romm", name: "Roman Mythology", id: 181 },
  { code: "rus", name: "Russian", id: 182 },
  { code: "sam", name: "Sami", id: 183 },
  { code: "sar", name: "Sardinian", id: 184 },
  { code: "sax", name: "Low German", id: 185 },
  { code: "scaa", name: "Ancient Scandinavian", id: 186 },
  { code: "scam", name: "Norse Mythology", id: 187 },
  { code: "sco", name: "Scottish", id: 188 },
  { code: "sct", name: "Scots", id: 189 },
  { code: "sen", name: "Seneca", id: 190 },
  { code: "ser", name: "Serbian", id: 191 },
  { code: "sha", name: "Shawnee", id: 192 },
  { code: "sho", name: "Shona", id: 193 },
  { code: "sic", name: "Sicilian", id: 194 },
  { code: "sik", name: "Siksika", id: 195 },
  { code: "sin", name: "Sinhalese", id: 196 },
  { code: "sio", name: "Sioux", id: 197 },
  { code: "sla", name: "Slavic", id: 198 },
  { code: "slam", name: "Slavic Mythology", id: 199 },
  { code: "slk", name: "Slovak", id: 200 },
  { code: "sln", name: "Slovene", id: 201 },
  { code: "smn", name: "Samoan", id: 202 },
  { code: "som", name: "Somali", id: 203 },
  { code: "sor", name: "Sorbian", id: 204 },
  { code: "sot", name: "Sotho", id: 205 },
  { code: "spa", name: "Spanish", id: 206 },
  { code: "swa", name: "Swahili", id: 207 },
  { code: "swe", name: "Swedish", id: 208 },
  { code: "swz", name: "Swazi", id: 209 },
  { code: "tag", name: "Tagalog", id: 210 },
  { code: "tah", name: "Tahitian", id: 211 },
  { code: "taj", name: "Tajik", id: 212 },
  { code: "tam", name: "Tamil", id: 213 },
  { code: "tat", name: "Tatar", id: 214 },
  { code: "tau", name: "Tausug", id: 215 },
  { code: "tel", name: "Telugu", id: 216 },
  { code: "theo", name: "Theology", id: 217 },
  { code: "tib", name: "Tibetan", id: 218 },
  { code: "tkm", name: "Turkmen", id: 219 },
  { code: "ton", name: "Tongan", id: 220 },
  { code: "too", name: "Tooro", id: 221 },
  { code: "trans", name: "Transformer", id: 222 },
  { code: "tsw", name: "Tswana", id: 223 },
  { code: "tum", name: "Tumbuka", id: 224 },
  { code: "tup", name: "Tupi", id: 225 },
  { code: "tur", name: "Turkish", id: 226 },
  { code: "ukr", name: "Ukrainian", id: 227 },
  { code: "urd", name: "Urdu", id: 228 },
  { code: "urh", name: "Urhobo", id: 229 },
  { code: "usa", name: "American", id: 230 },
  { code: "uyg", name: "Uyghur", id: 231 },
  { code: "uzb", name: "Uzbek", id: 232 },
  { code: "vari", name: "Various", id: 233 },
  { code: "vie", name: "Vietnamese", id: 234 },
  { code: "wel", name: "Welsh", id: 235 },
  { code: "witch", name: "Witch", id: 236 },
  { code: "wrest", name: "Wrestler", id: 237 },
  { code: "xho", name: "Xhosa", id: 238 },
  { code: "yao", name: "Yao", id: 239 },
  { code: "yol", name: "Yolngu", id: 240 },
  { code: "yor", name: "Yoruba", id: 241 },
  { code: "zap", name: "Zapotec", id: 242 },
  { code: "zul", name: "Zulu", id: 243 },
];

export default usage;
